const { chromium } = require('/opt/node-tools/node_modules/playwright');
const fs=require('fs');
const img=(p)=>'data:image/png;base64,'+fs.readFileSync(p).toString('base64');
const F="'IBM Plex Sans Arabic',sans-serif", M="'Montserrat',sans-serif";
const CSS=`*{box-sizing:border-box;margin:0;padding:0}html,body{font-family:${F};color:#12243D;background:#fff}
.pg{width:1920px;height:1080px;position:relative;overflow:hidden;page-break-after:always;background:#F3F7FB;padding:64px 80px}
.pg.dark{background:radial-gradient(900px 500px at 85% -10%,rgba(91,196,206,.18),transparent 60%),radial-gradient(700px 500px at 0% 100%,rgba(24,85,164,.4),transparent 60%),linear-gradient(160deg,#050E1F 0%,#0A1A36 55%,#071429 100%);color:#F2F7FC}
.hd{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:34px;border-bottom:2px solid #E2EAF3;padding-bottom:18px}.dark .hd{border-color:rgba(91,196,206,.25)}
.hd h1{font-size:44px;font-weight:700}.hd .k{font-size:18px;color:#5B6F8A;font-family:${M};font-weight:800;font-style:italic;letter-spacing:.05em}.dark .hd .k{color:#5BC4CE}
.hd .sub{font-size:20px;color:#5B6F8A;margin-top:6px}.dark .hd .sub{color:#A9BFD6}
.logo{display:flex;align-items:center;gap:12px;direction:rtl}.logo .ar{font-size:40px;font-weight:700}.logo .vl{width:4px;height:36px;border-radius:4px;background:linear-gradient(180deg,#1855A4,#5BC4CE)}.logo .en{font-family:${M};font-style:italic;font-weight:800;font-size:28px;color:#1855A4}.dark .logo .en{color:#5BC4CE}
.ft{position:absolute;bottom:28px;left:80px;right:80px;display:flex;justify-content:space-between;font-size:15px;color:#8A9BB2}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:28px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:28px}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}
.card{background:#fff;border:1px solid #E2EAF3;border-radius:18px;padding:24px 28px;box-shadow:0 6px 18px rgba(18,36,61,.05)}.dark .card{background:rgba(16,32,60,.8);border-color:rgba(91,196,206,.18)}
.card h3{font-size:24px;margin-bottom:12px}.card p,.card li{font-size:18px;line-height:1.7;color:#3D5270}.dark .card p,.dark .card li{color:#CFE1EF}
ul{list-style:none}li::before{content:'•';color:#5BC4CE;font-weight:700;margin-inline-end:10px}
.shot{border-radius:14px;overflow:hidden;border:1px solid #E2EAF3;box-shadow:0 14px 34px rgba(18,36,61,.14);background:#000}.shot img{width:100%;display:block}.shot.side{height:290px}.shot.side img{height:auto}
.cap{font-size:17px;color:#5B6F8A;margin-top:10px;text-align:center}.dark .cap{color:#A9BFD6}
.tag{display:inline-block;font-size:15px;font-weight:700;padding:5px 14px;border-radius:999px;background:rgba(24,85,164,.12);color:#1855A4;margin-bottom:10px}.dark .tag{background:rgba(91,196,206,.14);color:#5BC4CE}
.sw{display:flex;gap:14px;flex-wrap:wrap}.sw div{width:150px;border-radius:14px;padding:12px;color:#fff;font-size:14px;height:110px;display:flex;flex-direction:column;justify-content:flex-end;font-family:${M};direction:ltr}.sw div b{font-family:${F};font-size:15px;display:block;margin-bottom:2px}
.wf{background:#fff;border:2px solid #C9D8E8;border-radius:14px;padding:14px;height:420px;position:relative}.wf .b{background:#E2EAF3;border-radius:6px}.wf .l{background:#C9D8E8;border-radius:4px;height:10px}
.flow{display:flex;align-items:stretch;gap:0;margin-top:10px}.step{flex:1;background:#fff;border:1px solid #E2EAF3;border-radius:16px;padding:20px 18px;position:relative}.step .n{width:36px;height:36px;border-radius:50%;background:linear-gradient(135deg,#1855A4,#5BC4CE);color:#fff;display:grid;place-items:center;font-weight:700;font-size:17px;margin-bottom:12px}.step h4{font-size:20px;margin-bottom:6px}.step p{font-size:15.5px;color:#5B6F8A;line-height:1.6}
.arrow{width:34px;display:grid;place-items:center;color:#5BC4CE;font-size:30px;font-weight:700}
.phones{display:flex;justify-content:space-between;gap:24px}.phone{width:356px;border-radius:38px;border:10px solid #12243D;overflow:hidden;background:#000;box-shadow:0 20px 50px rgba(0,0,0,.25)}.phone img{width:100%;display:block}
table.cmp{width:100%;border-collapse:collapse;font-size:18px}table.cmp th{background:#1855A4;color:#fff;padding:14px;text-align:right;font-weight:700}table.cmp td{padding:14px;border-bottom:1px solid #E2EAF3;background:#fff;line-height:1.6}table.cmp td:first-child{font-weight:700}
.badge{font-size:14px;padding:3px 10px;border-radius:999px;font-weight:700;display:inline-block}.b-inst{background:rgba(228,87,61,.12);color:#C8432A;border:1px solid rgba(228,87,61,.35)}.b-cum{background:rgba(217,138,30,.12);color:#B8700F;border:1px solid rgba(217,138,30,.35)}
.btn{display:inline-block;padding:10px 18px;border-radius:10px;font-weight:700;font-size:15px;border:1px solid #E2EAF3;background:#fff}.btn.p{background:linear-gradient(90deg,#1855A4,#5BC4CE);color:#fff;border-color:transparent}
.chip{display:inline-block;border:1px solid #E2EAF3;background:#fff;border-radius:999px;padding:6px 14px;font-size:14px;font-weight:600}.chip.on{background:linear-gradient(90deg,#1855A4,#5BC4CE);color:#fff;border-color:transparent}
.kpi{display:flex;gap:12px;align-items:center;background:#fff;border:1px solid #E2EAF3;border-radius:14px;padding:12px 16px;width:220px}.kpi .ic{width:40px;height:40px;border-radius:12px;background:rgba(228,87,61,.14)}.kpi b{font-size:26px;display:block;line-height:1}.kpi span{font-size:12px;color:#5B6F8A}
.rec{background:linear-gradient(135deg,rgba(24,85,164,.10),rgba(91,196,206,.14));border:1px solid rgba(24,85,164,.25);border-radius:18px;padding:22px 28px;margin-top:24px}.rec h3{font-size:24px;margin-bottom:8px;color:#1855A4}.rec p{font-size:18px;line-height:1.7}`;
const hd=(t,sub,k)=>`<div class="hd"><div><h1>${t}</h1>${sub?`<div class="sub">${sub}</div>`:''}</div><div style="text-align:left"><div class="logo"><span class="ar">أثر</span><span class="vl"></span><span class="en">ATHAR</span></div><div class="k">${k||'UI/UX DESIGN · HEALTHON 2026'}</div></div></div>`;
const ft=(n)=>`<div class="ft"><span>أثر — Silent Experience Intelligence Engine · ملف تصميم واجهات وتجربة المستخدم</span><span>هيلثون 2026 · صفحة ${n} / 12</span></div>`;
const pages=[];
// 1 cover
pages.push(`<div class="pg dark" style="display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center">
<div class="logo" style="gap:26px"><span class="ar" style="font-size:150px">أثر</span><span class="vl" style="height:120px;width:10px"></span><span class="en" style="font-size:96px">ATHAR</span></div>
<div style="font-family:${M};font-style:italic;font-weight:800;font-size:26px;color:#A9BFD6;letter-spacing:.05em;direction:ltr;margin-top:6px">Silent Experience Intelligence Engine</div>
<h1 style="font-size:56px;margin-top:60px">ملف تصميم واجهات وتجربة المستخدم</h1><div style="font-size:28px;color:#CFE1EF;margin-top:14px">UI/UX Design · أربعة مقترحات تصميمية لمركز قيادة تجربة المريض</div>
<div style="display:flex;gap:16px;margin-top:40px"><span class="tag">المقترح 1 · مركز القيادة الداكن</span><span class="tag">المقترح 2 · الوضع الفاتح السريري</span><span class="tag">المقترح 3 · تطبيق الجوال</span><span class="tag">المقترح 4 · لوحة حائط القسم</span></div>
<div style="position:absolute;bottom:40px;font-size:18px;color:#7F94AE">هيلثون 2026 · نموذج تفاعلي توضيحي ببيانات اصطناعية · بلا ربط فعلي بأنظمة المنشأة</div></div>`);
// 2 overview
pages.push(`<div class="pg">${hd('نظرة عامة على التصميم','لمن نصمّم، وما المشكلة، وما المبادئ التي تحكم كل شاشة')}
<div class="grid3"><div class="card"><span class="tag">المشكلة</span><h3>تعثّر صامت في رحلة المريض</h3><p>كثير من المرضى لا يشتكون؛ ينتظرون طويلًا، يتنقلون في المكان الخطأ، أو تتعطل خدمتهم بموافقة معلقة. تصل الإشارة إلى فريق تجربة المريض متأخرة أو لا تصل.</p></div>
<div class="card"><span class="tag">المستخدمون</span><h3>ثلاث شخصيات رئيسية</h3><ul><li><b>مسؤول تجربة المريض</b>: يراقب، يرتّب الأولويات، يتواصل ويوثّق.</li><li><b>فريق القسم / التمريض</b>: يستلم الإسناد وينفذ الإجراء.</li><li><b>المريض</b>: يمنح أو يسحب موافقة تحديد الموقع.</li></ul></div>
<div class="card"><span class="tag">الحل</span><h3>مركز قيادة بإشارات مترابطة</h3><p>يجمع أثر أحداث الرحلة من الأنظمة المرتبطة، ويحوّلها إلى تنبيه فوري أو أولوية تراكمية مفسَّرة، ثم يتابع الحالة حتى توثيق النتيجة.</p></div></div>
<div class="grid4" style="margin-top:28px">${[['الإنسان في الحلقة','النظام يقترح ويرتّب ويشرح السبب؛ الفريق يقرر.'],['الشفافية','كل درجة لها تفسير: الإشارة، الوزن، المصدر، وهل احتُسبت.'],['تقليل البيانات','أحداث الرحلة فقط دون الوصول إلى السجل الطبي.'],['الموافقة أولًا','الموقع اختياري، خلال الزيارة فقط، وقابل للسحب.']].map(([a,b])=>`<div class="card"><h3 style="color:#1855A4">${a}</h3><p>${b}</p></div>`).join('')}</div>${ft(2)}</div>`);
// 3 flow
pages.push(`<div class="pg">${hd('تدفق المستخدم (User Flow)','من الإشارة إلى النتيجة الموثقة: رحلة مسؤول تجربة المريض داخل أثر')}
<div class="flow">${[['إشارات','أحداث من المواعيد والطوابير والتأمين والموقع (بموافقة).'],['ترتيب','تنبيه فوري عند تجاوز الانتظار 30 د، أو أولوية تراكمية بالأوزان.'],['مركز القيادة','مؤشرات وبطاقات حالات مرتبة بالأولوية.'],['فتح الحالة','الخط الزمني، الموقع والموافقة، درجة الأولوية وتفسيرها.'],['تواصل وتحقق','نتيجة التواصل ثم نتيجة التحقق من الاحتياج.'],['إجراء وإسناد','وصف الإجراء والجهة المسند إليها وموعد المتابعة.'],['توثيق','حالة المعالجة ووصف النتيجة وطريقة التحقق في السجل.'],['تحليل','توزيع الحالات وزمن التواصل ونقاط الخدمة الأكثر ظهورًا.']].map((s,i,a)=>`<div class="step"><div class="n">${i+1}</div><h4>${s[0]}</h4><p>${s[1]}</p></div>${i<a.length-1?'<div class="arrow">←</div>':''}`).join('')}</div>
<div class="grid2" style="margin-top:34px"><div class="card"><h3>قواعد تحكم الواجهة</h3><ul><li>التنبيه الفوري يبقى ظاهرًا حتى يراجعه الفريق، حتى لو كانت الدرجة التراكمية منخفضة.</li><li>«لم يرد» لا يسمح بإغلاق الحالة بوصفها «تمت المعالجة».</li><li>«تمت المعالجة» تتطلب وصف النتيجة وكيفية التحقق منها.</li><li>الواقعة الواحدة تُحتسب مرة واحدة فقط.</li></ul></div>
<div class="card"><h3>عتبات توضيحية</h3><ul><li>أقل من 40 نقطة: أولوية تراكمية منخفضة.</li><li>من 40 إلى 69: متوسطة.</li><li>70 فأكثر: مرتفعة.</li><li>حد الانتظار للتنبيه الفوري: 30 دقيقة. جميعها تحتاج إلى معايرة ميدانية.</li></ul></div></div>${ft(3)}</div>`);
// 4 design system
pages.push(`<div class="pg">${hd('نظام التصميم (Design System)','الألوان والخطوط والمكونات المشتركة بين جميع المقترحات')}
<div class="grid2"><div class="card"><h3>لوحة الألوان</h3><div class="sw">${[['#050E1F','كحلي عميق','الخلفية'],['#1855A4','أزرق أثر','الأساسي'],['#5BC4CE','تركواز','التمييز'],['#FF5D5D','أحمر','تنبيه فوري'],['#F2A93B','برتقالي','أولوية تراكمية'],['#4CC38A','أخضر','تمت المعالجة'],['#8FA9C8','رمادي مزرق','محايد'],['#F3F7FB','فاتح','خلفية فاتحة']].map(([c,n,u])=>`<div style="background:${c};${c==='#F3F7FB'?'color:#12243D;border:1px solid #E2EAF3':''}"><b>${n} · ${u}</b>${c}</div>`).join('')}</div>
<h3 style="margin-top:22px">الخطوط</h3><p style="font-size:30px;font-weight:700">IBM Plex Sans Arabic — العناوين والنصوص</p><p style="font-family:${M};font-style:italic;font-weight:800;font-size:28px;direction:ltr;text-align:left;color:#1855A4">Montserrat ExtraBold Italic — ATHAR</p><p>الأحجام: 26/18/15.5 للويب، 15/12/11 للجوال. اتجاه RTL أصلي مع دعم الإنجليزية.</p></div>
<div class="card"><h3>المكونات</h3><div style="display:flex;flex-direction:column;gap:18px">
<div><p style="font-weight:700">شارات نوع التنبيه</p><span class="badge b-inst">● تنبيه فوري</span> <span class="badge b-cum">▲ أولوية تراكمية</span></div>
<div><p style="font-weight:700">مستويات الأولوية</p><span class="chip">أولوية تراكمية منخفضة</span> <span class="chip" style="background:rgba(217,138,30,.14);color:#B8700F;border-color:transparent">متوسطة</span> <span class="chip" style="background:rgba(228,87,61,.14);color:#C8432A;border-color:transparent">مرتفعة</span></div>
<div><p style="font-weight:700">أزرار</p><span class="btn p">لماذا ظهرت هذه الأولوية؟</span> <span class="btn">إعادة ضبط السيناريو</span></div>
<div><p style="font-weight:700">مرشحات</p><span class="chip on">الكل</span> <span class="chip">تنبيهات فورية</span> <span class="chip">أولوية تراكمية</span> <span class="chip">قيد المعالجة</span></div>
<div><p style="font-weight:700">بطاقة مؤشر</p><div class="kpi"><div class="ic"></div><div><b>3</b><span>تنبيهات فورية مفتوحة</span></div></div></div>
<div><p style="font-weight:700">حالات المعالجة</p><span class="chip">قيد المراجعة</span> <span class="chip" style="color:#1C8FA0">جارٍ التواصل</span> <span class="chip" style="color:#1C8FA0">قيد المعالجة</span> <span class="chip" style="color:#2E9E6C">تمت المعالجة</span> <span class="chip" style="color:#C8432A">تم التصعيد</span></div></div></div></div>${ft(4)}</div>`);
// 5 wireframes
const wfHome=`<div class="wf"><div style="display:flex;gap:10px;height:100%"><div style="flex:1;display:flex;flex-direction:column;gap:10px"><div class="b" style="height:34px"></div><div class="b" style="height:70px;background:#C9D8E8"></div><div style="display:flex;gap:8px">${'<div class="b" style="flex:1;height:60px"></div>'.repeat(4)}</div><div style="display:flex;gap:6px">${'<div class="b" style="width:70px;height:22px;border-radius:11px"></div>'.repeat(4)}</div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;flex:1">${'<div class="b" style="min-height:70px"></div>'.repeat(6)}</div></div><div style="width:90px;display:flex;flex-direction:column;gap:8px"><div class="b" style="height:40px;background:#C9D8E8"></div>${'<div class="l"></div>'.repeat(4)}</div></div></div>`;
const wfCase=`<div class="wf"><div style="display:flex;gap:10px;height:100%"><div style="flex:1;display:flex;flex-direction:column;gap:10px"><div class="b" style="height:60px;background:#C9D8E8"></div><div style="display:flex;gap:10px;flex:1"><div style="flex:1;display:flex;flex-direction:column;gap:8px"><div class="b" style="height:50px;border:2px solid #FF5D5D;background:rgba(255,93,93,.12)"></div><div class="b" style="height:70px"></div><div class="b" style="flex:1"></div></div><div style="flex:1;display:flex;flex-direction:column;gap:8px"><div class="b" style="height:80px"></div><div class="b" style="height:60px"></div><div class="b" style="flex:1"></div></div></div></div><div style="width:90px;display:flex;flex-direction:column;gap:8px"><div class="b" style="height:40px;background:#C9D8E8"></div>${'<div class="l"></div>'.repeat(4)}</div></div></div>`;
const wfAn=`<div class="wf"><div style="display:flex;gap:10px;height:100%"><div style="flex:1;display:flex;flex-direction:column;gap:10px"><div class="b" style="height:60px;background:#C9D8E8"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;flex:1">${'<div class="b" style="padding:10px;display:flex;flex-direction:column;gap:6px;justify-content:center"><div class="l" style="width:80%"></div><div class="l" style="width:60%"></div><div class="l" style="width:40%"></div></div>'.repeat(4)}</div><div class="b" style="height:60px"></div></div><div style="width:90px;display:flex;flex-direction:column;gap:8px"><div class="b" style="height:40px;background:#C9D8E8"></div>${'<div class="l"></div>'.repeat(4)}</div></div></div>`;
pages.push(`<div class="pg">${hd('الرسومات الأولية (Low-fidelity Wireframes)','هيكل الشاشات قبل التصميم النهائي: التنقل الجانبي ثابت، والمحتوى مرتب بالأولوية')}
<div class="grid3"><div>${wfHome}<div class="cap">مركز القيادة: ترويسة، 4 مؤشرات، مرشحات، شبكة بطاقات الحالات</div></div><div>${wfCase}<div class="cap">تفاصيل الحالة: عمودان — التنبيه والمحاكاة والخط الزمني يمينًا؛ الدرجة والتوثيق والسجل يسارًا</div></div><div>${wfAn}<div class="cap">التحليلات: شبكة بطاقات بيانية وجدول التعثّر والإجراء</div></div></div>
<div class="card" style="margin-top:28px"><h3>قرارات الهيكل</h3><ul><li>الشريط الجانبي ثابت في اليمين (RTL) بأربعة أقسام فقط: مركز القيادة، الحالات، التحليلات، الإعدادات.</li><li>التنبيه الفوري يأخذ أول موضع في عمود المعلومات داخل الحالة ليُقرأ قبل أي شيء آخر.</li><li>نموذج التحديث مرتب بالترتيب المنطقي: التواصل ← التحقق ← الإجراء ← حالة المعالجة.</li></ul></div>${ft(5)}</div>`);
// 6 proposal 1 dark
pages.push(`<div class="pg dark">${hd('المقترح 1 · مركز القيادة الداكن','واجهة سطح مكتب لغرفة العمليات: تباين عالٍ، إشارات ملوّنة، مناسبة للشاشات الكبيرة والعمل الطويل','PROPOSAL 1 · DARK COMMAND CENTER')}
<div style="display:grid;grid-template-columns:1.25fr 1fr;gap:26px"><div><div class="shot"><img src="${img('ux/dark_home.png')}"></div><div class="cap">مركز القيادة: المؤشرات الأربعة وبطاقات الحالات؛ الإطار الأحمر للحالات ذات التنبيه الفوري</div></div>
<div style="display:flex;flex-direction:column;gap:20px"><div><div class="shot side"><img src="${img('ux/dark_case.png')}"></div><div class="cap">تفاصيل الحالة أ-03 مع التنبيه الفوري ودرجة الأولوية</div></div><div><div class="shot side"><img src="${img('ux/dark_analytics.png')}"></div><div class="cap">التحليلات</div></div></div></div>
<div style="display:flex;gap:16px;margin-top:18px"><span class="tag">الأنسب لـ: غرفة عمليات تجربة المريض</span><span class="tag">نقطة القوة: وضوح الإشارات الحمراء والبرتقالية</span><span class="tag">ملاحظة: يحتاج ضبط سطوع للطباعة</span></div>${ft(6)}</div>`);
// 7 proposal 2 light
pages.push(`<div class="pg">${hd('المقترح 2 · الوضع الفاتح السريري','النظام نفسه بسمة فاتحة تناسب بيئة العيادات والإضاءة القوية والطباعة والتقارير','PROPOSAL 2 · CLINICAL LIGHT')}
<div style="display:grid;grid-template-columns:1.25fr 1fr;gap:26px"><div><div class="shot"><img src="${img('ux/light_home.png')}"></div><div class="cap">مركز القيادة بالوضع الفاتح: الشريط الجانبي يبقى داكنًا لتثبيت الهوية</div></div>
<div style="display:flex;flex-direction:column;gap:20px"><div><div class="shot side"><img src="${img('ux/light_case.png')}"></div><div class="cap">تفاصيل الحالة</div></div><div><div class="shot side"><img src="${img('ux/light_analytics.png')}"></div><div class="cap">التحليلات</div></div></div></div>
<div style="display:flex;gap:16px;margin-top:18px"><span class="tag">الأنسب لـ: مكاتب الأقسام والمستخدمين النهاريين</span><span class="tag">نقطة القوة: قابلية القراءة والطباعة</span><span class="tag">قابل للتبديل من الإعدادات بنقرة واحدة</span></div>${ft(7)}</div>`);
// 8 proposal 3 mobile
pages.push(`<div class="pg">${hd('المقترح 3 · تطبيق الجوال','لمسؤول تجربة المريض أثناء التنقل في الأقسام، وشاشة موافقة المريض على هاتفه','PROPOSAL 3 · MOBILE APP')}
<div class="phones"><div><div class="phone"><img src="${img('ux/m1.png')}"></div><div class="cap">مركز القيادة: مؤشرات مضغوطة وقائمة حالات مرتبة</div></div><div><div class="phone"><img src="${img('ux/m2.png')}"></div><div class="cap">تفاصيل الحالة: التنبيه الفوري ثم الدرجة وزر «لماذا؟»</div></div><div><div class="phone"><img src="${img('ux/m3.png')}"></div><div class="cap">تحديث الحالة: تواصل ← تحقق ← إجراء ← حالة</div></div><div><div class="phone"><img src="${img('ux/m4.png')}"></div><div class="cap">شاشة المريض: موافقة صريحة قابلة للسحب</div></div></div>${ft(8)}</div>`);
// 9 proposal 4 wallboard
pages.push(`<div class="pg dark">${hd('المقترح 4 · لوحة حائط القسم','شاشة تلفاز في مكتب القسم تعرض ما يحتاج تواصلًا الآن دون أي تفاعل، بخط كبير يُقرأ من بعيد','PROPOSAL 4 · DEPARTMENT WALLBOARD')}
<div class="shot" style="max-width:1180px;margin:0 auto"><img src="${img('ux/wallboard.png')}"></div>
<div style="display:flex;gap:16px;margin-top:18px;justify-content:center"><span class="tag">بدون بيانات تعريفية للمريض: رقم الحالة والقسم فقط</span><span class="tag">تحديث تلقائي كل دقيقة</span><span class="tag">لا يُستخدم لتقييم الموظفين أفرادًا</span></div>${ft(9)}</div>`);
// 10 comparison
pages.push(`<div class="pg">${hd('مقارنة المقترحات والتوصية','أي مقترح لأي سياق؟ وكيف تتكامل معًا على نظام تصميم واحد')}
<table class="cmp"><tr><th>المقترح</th><th>المستخدم الأساسي</th><th>السياق</th><th>نقاط القوة</th><th>القيود</th></tr>
<tr><td>1 · مركز القيادة الداكن</td><td>مسؤول تجربة المريض</td><td>غرفة عمليات، شاشة كبيرة، عمل متواصل</td><td>تباين عالٍ، الإشارات الحمراء والبرتقالية بارزة، هوية قوية</td><td>أقل ملاءمة للطباعة والإضاءة الساطعة</td></tr>
<tr><td>2 · الوضع الفاتح السريري</td><td>فرق الأقسام والمشرفون</td><td>مكاتب الأقسام، التقارير، العرض على بروجكتر</td><td>قراءة مريحة، طباعة واضحة، مألوف لأنظمة المستشفى</td><td>الشارات الملوّنة أقل بروزًا</td></tr>
<tr><td>3 · تطبيق الجوال</td><td>المسؤول المتنقل + المريض</td><td>الجولات الميدانية، التواصل الفوري، الموافقة</td><td>وصول سريع للحالة والتوثيق في المكان، موافقة شفافة للمريض</td><td>مساحة محدودة للتحليلات</td></tr>
<tr><td>4 · لوحة حائط القسم</td><td>فريق القسم كله</td><td>شاشة تلفاز بدون تفاعل</td><td>وعي جماعي فوري بما يحتاج تواصلًا الآن</td><td>عرض فقط؛ لا توثيق ولا تفاصيل</td></tr></table>
<div class="rec"><h3>التوصية</h3><p>اعتماد <b>المقترح 1</b> واجهةً أساسية للتجربة الأولية (وهو المنفَّذ فعلًا في النموذج التفاعلي)، مع <b>المقترح 2</b> سمةً قابلة للتبديل من الإعدادات. يُضاف <b>المقترح 3</b> في المرحلة الثانية لشاشة موافقة المريض والتوثيق الميداني، و<b>المقترح 4</b> كتوسع اختياري للأقسام ذات الحجم الكبير. المقترحات الأربعة تشترك في نظام التصميم نفسه، فلا تكلفة هوية إضافية.</p></div>${ft(10)}</div>`);
// 11 accessibility
pages.push(`<div class="pg">${hd('إمكانية الوصول واعتبارات الاستخدام','ما يضمن أن الواجهة مفهومة وآمنة ومحترمة للخصوصية')}
<div class="grid3"><div class="card"><h3>القراءة والتباين</h3><ul><li>تباين نص/خلفية لا يقل عن 4.5:1 في السمتين.</li><li>الحالة لا تُنقل باللون وحده: شارة نصية + أيقونة لكل نوع تنبيه.</li><li>الحد الأدنى للخط 15.5px على الويب و11px على الجوال.</li></ul></div>
<div class="card"><h3>اللغة والاتجاه</h3><ul><li>RTL أصلي مع تبديل كامل إلى الإنجليزية من زر واحد.</li><li>الأرقام والأوقات بصيغة موحدة (09:43) في اللغتين.</li><li>مصطلحات ثابتة: تنبيه فوري، أولوية تراكمية، درجة أولوية التواصل.</li></ul></div>
<div class="card"><h3>الخصوصية والأخلاقيات</h3><ul><li>لا بيانات طبية في أي شاشة؛ أحداث الرحلة فقط.</li><li>شاشة الموافقة تشرح النطاق والمدة وحق السحب بلغة بسيطة.</li><li>لوحة الحائط تعرض رقم الحالة والقسم دون اسم.</li><li>لا يُستخدم النظام لتقييم الموظفين أفرادًا.</li></ul></div></div>
<div class="grid2" style="margin-top:28px"><div class="card"><h3>حالات الخطأ والحواف</h3><ul><li>رسائل تحقق واضحة عند محاولة إغلاق الحالة دون نتيجة موثقة.</li><li>حالة «لا توجد حالات مطابقة» عند التصفية.</li><li>انتهاء شرط التنبيه لا يغلق الحالة تلقائيًا؛ تبقى للمراجعة.</li></ul></div>
<div class="card"><h3>قابلية التفسير</h3><ul><li>زر «لماذا ظهرت هذه الأولوية؟» متاح في كل حالة ويعرض جدول الإشارات كاملًا.</li><li>العتبات والأوزان معروضة في الإعدادات بوصفها قيمًا توضيحية تحتاج معايرة.</li></ul></div></div>${ft(11)}</div>`);
// 12 handoff
pages.push(`<div class="pg dark">${hd('ملاحظات التسليم والمصادر','كيف تُستخدم هذه الملفات داخل Figma وما الذي يرافقها','HANDOFF')}
<div class="grid2"><div class="card"><h3>الاستيراد إلى Figma</h3><ul><li>الشاشات النهائية في المقترحين 1 و2 مصدرها الحقيقي ملف HTML واحد (index.html) يمكن استيراده إلى Figma كطبقات قابلة للتعديل عبر إضافة html.to.design.</li><li>شاشات الجوال ولوحة الحائط مبنية بالطريقة نفسها (ملفات HTML مرفقة في المستودع تحت media/ux-source).</li><li>الصور بدقة 2x–3x جاهزة للصق المباشر في أي لوحة Figma.</li></ul></div>
<div class="card"><h3>محتويات الحزمة</h3><ul><li>هذا الملف: ATHAR_UIUX_Design.pdf (12 صفحة).</li><li>الشاشات: media/ux/ — داكن، فاتح، جوال، لوحة حائط.</li><li>اللوقو: media/logo/ — داكن، فاتح، شفاف، مربع.</li><li>الفيديو التوضيحي: media/ATHAR_Demo_Video.mp4 (60 ثانية).</li><li>النموذج التفاعلي: index.html يعمل في المتصفح مباشرة.</li></ul></div></div>
<div class="card" style="margin-top:26px"><h3>الخطوات التالية المقترحة</h3><ul><li>اختبار قابلية الاستخدام مع 3–5 مسؤولي تجربة مريض على السيناريو أ-03.</li><li>معايرة العتبات (30 د، 40/70) والأوزان مع بيانات ميدانية.</li><li>اعتماد الوضع الفاتح أو الداكن افتراضيًا حسب موقع التشغيل.</li></ul></div>${ft(12)}</div>`);
const html=`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><style>${CSS}@page{size:1920px 1080px;margin:0}</style></head><body>${pages.join('')}</body></html>`;
fs.writeFileSync('ux/deck.html',html);
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1920,height:1080}});await p.setContent(html);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(800);
 await p.pdf({path:'ATHAR_UIUX_Design.pdf',width:'1920px',height:'1080px',printBackground:true,preferCSSPageSize:true});
 // page previews
 const n=await p.evaluate(()=>document.querySelectorAll('.pg').length);
 for(let i=0;i<n;i++){ const el=(await p.$$('.pg'))[i]; await el.screenshot({path:`ux/page${String(i+1).padStart(2,'0')}.png`}); }
 console.log('pages',n); await b.close();})();
