-- ATHAR demo seed data. Synthetic illustrative data only; not real patients.
INSERT INTO departments VALUES ('ob','النساء والولادة','OB/GYN');
INSERT INTO departments VALUES ('or','العظام','Orthopedics');
INSERT INTO departments VALUES ('im','الباطنة','Internal Medicine');
INSERT INTO departments VALUES ('de','الجلدية','Dermatology');
INSERT INTO departments VALUES ('ca','القلب','Cardiology');
INSERT INTO departments VALUES ('em','الطوارئ','Emergency');
INSERT INTO places VALUES ('reg','التسجيل','Registration');
INSERT INTO places VALUES ('cw','انتظار العيادة','Clinic waiting');
INSERT INTO places VALUES ('cl','العيادة','Clinic');
INSERT INTO places VALUES ('rad','منطقة الأشعة','Radiology zone');
INSERT INTO places VALUES ('ins','نافذة التأمين','Insurance desk');
INSERT INTO places VALUES ('ph','الصيدلية','Pharmacy');
INSERT INTO places VALUES ('ent','المدخل','Entrance');
INSERT INTO places VALUES ('lab','المختبر','Laboratory');
INSERT INTO places VALUES ('er','الطوارئ','Emergency');
INSERT INTO signal_types VALUES ('resched',8,'تكرار إعادة الجدولة من مقدم الخدمة','Repeated provider-initiated rescheduling','نظام المواعيد','Appointments system');
INSERT INTO signal_types VALUES ('wait',12,'انتظار يتجاوز الحد التوضيحي (30 د)','Waiting above illustrative limit (30 min)','نظام الطوابير','Queue system');
INSERT INTO signal_types VALUES ('move',10,'تنقل غير متوقع مقارنة بالمسار المتوقع','Unexpected movement vs expected path','تحديد الموقع الداخلي (محاكاة)','Indoor positioning (simulated)');
INSERT INTO signal_types VALUES ('ret',10,'عودة غير متوقعة إلى محطة سابقة','Unexpected return to an earlier station','تحديد الموقع الداخلي (محاكاة)','Indoor positioning (simulated)');
INSERT INTO signal_types VALUES ('appr',10,'موافقة معلقة تعيق الخدمة','Pending approval blocking service','نظام التأمين والموافقات','Insurance & approvals system');
INSERT INTO thresholds VALUES ('cumulative_medium',40,'من 40 إلى 69: أولوية تراكمية متوسطة');
INSERT INTO thresholds VALUES ('cumulative_high',70,'70 فأكثر: أولوية تراكمية مرتفعة');
INSERT INTO thresholds VALUES ('instant_wait_limit_minutes',30,'حد الانتظار التوضيحي للتنبيه الفوري');
INSERT INTO cases VALUES ('A-01','الحالة أ-01','Case A-01',34,'ob','review',0,'none',NULL,NULL,'open','10:35','انتظار 41 دقيقة — 11 دقيقة فوق الحد التوضيحي','41 min wait — 11 min over illustrative limit');
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-01','wait',12,'active','sys','wait-j5icn',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-01','التسجيل','Registration','10:02','10:04','reg','sys','نظام معلومات المستشفى','HIS','off',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-01','انتظار العيادة (41 د حتى الآن)','Clinic waiting (41 min so far)','10:05','10:46','cw','sys','نظام الطوابير','Queue system','on',NULL,NULL);
INSERT INTO case_updates VALUES ('A-01','none','open',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-01','10:35','lg_alert','انتظار يتجاوز الحد التوضيحي','waiting above illustrative limit');
INSERT INTO cases VALUES ('A-02','الحالة أ-02','Case A-02',45,'or','contacting',0,'granted','08:51','09:58',NULL,NULL,NULL,NULL);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-02','resched',8,'active','sys','resched-awzja',1);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-02','appr',10,'active','sys','appr-f5b9u',1);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-02','ret',10,'active','loc','ret-nah7j',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-02','إعادة جدولة الموعد مرتين من مقدم الخدمة','Appointment rescheduled twice by provider','—','—',NULL,'sys','نظام المواعيد','Appointments system','off',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-02','موافقة تأمين معلقة لإجراء الأشعة','Insurance approval pending for imaging','09:20','09:58','ins','sys','نظام التأمين والموافقات','Insurance & approvals','on',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-02','عودة إلى نافذة التسجيل بعد بدء الخدمة','Returned to registration after service start','09:41','09:44','reg','loc','تحديد الموقع الداخلي (محاكاة)','Indoor positioning (simulated)','off',NULL,NULL);
INSERT INTO case_updates VALUES ('A-02','ok','open','متابعة الموافقة مع شؤون التأمين','فريق تجربة المريض','شؤون التأمين',NULL,NULL,NULL);
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-02','09:46','lg_signal','اجتماع 3 إشارات مؤهلة','3 qualifying signals combined');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-02','09:50','lg_assign','شؤون التأمين','Insurance affairs');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-02','09:55','lg_contact','تم التواصل','Contacted');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',1,'ent');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',2,'reg');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',3,'cw');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',4,'cl');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',5,'ins');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-02',6,'reg');
INSERT INTO cases VALUES ('A-03','الحالة أ-03','Case A-03',58,'im','review',1,'none',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-03','resched',8,'active','sys','ev-resched',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-03','تكرار إعادة الجدولة من مقدم الخدمة','Repeated provider-initiated rescheduling','—','—',NULL,'sys','نظام المواعيد','Appointments system','off',NULL,NULL);
INSERT INTO case_updates VALUES ('A-03','none','open',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-03','—','lg_signal','تكرار إعادة الجدولة (8 نقاط)','Repeated rescheduling (8 pts)');
INSERT INTO cases VALUES ('A-04','الحالة أ-04','Case A-04',29,'de','review',0,'granted','09:02','10:30','open','10:21','انتظار 36 دقيقة — 6 دقائق فوق الحد التوضيحي','36 min wait — 6 min over illustrative limit');
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-04','resched',8,'active','sys','resched-e88rr',1);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-04','wait',12,'active','sys','wait-au3gz',1);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-04','appr',10,'active','sys','appr-gbhl0',1);
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-04','move',10,'active','loc','move-qeq40',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-04','إعادة جدولة الموعد مرتين من مقدم الخدمة','Appointment rescheduled twice by provider','—','—',NULL,'sys','نظام المواعيد','Appointments system','off',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-04','توجه إلى المختبر دون طلب تحاليل في الزيارة','Went to the lab with no lab order in the visit','09:31','09:39','lab','loc','تحديد الموقع الداخلي (محاكاة)','Indoor positioning (simulated)','off',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-04','موافقة معلقة لإجراء جلدي','Approval pending for dermatology procedure','09:45','10:30','ins','sys','نظام التأمين والموافقات','Insurance & approvals','on',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-04','انتظار العيادة (36 د حتى الآن)','Clinic waiting (36 min so far)','09:51','10:27','cw','sys','نظام الطوابير','Queue system','on',NULL,NULL);
INSERT INTO case_updates VALUES ('A-04','none','open',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-04','10:21','lg_alert','انتظار يتجاوز الحد التوضيحي','waiting above illustrative limit');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',1,'ent');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',2,'reg');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',3,'lab');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',4,'cw');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',5,'ins');
INSERT INTO location_pings (case_id,seq,place_code) VALUES ('A-04',6,'cw');
INSERT INTO cases VALUES ('A-05','الحالة أ-05','Case A-05',62,'ca','resolved',0,'denied','08:40',NULL,'closed','09:20','انتظار 34 دقيقة','34 min wait');
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-05','wait',12,'hist','sys','wait-o49yn',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-05','انتظار العيادة 44 دقيقة (14 فوق الحد)','Clinic waiting 44 min (14 over limit)','08:46','09:30','cw','sys','نظام الطوابير','Queue system','off',NULL,NULL);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-05','بدء خدمة العيادة','Clinic service started','09:30','09:52','cl','sys','نظام معلومات المستشفى','HIS','off',NULL,NULL);
INSERT INTO case_updates VALUES ('A-05','ok','need','اعتذار وتنسيق أولوية الدخول للطبيب','فريق تجربة المريض','تمريض العيادة',NULL,'دخل المريض للطبيب خلال 8 دقائق من التواصل','حدث بدء الخدمة في النظام + تأكيد شفهي من المريض');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-05','09:20','lg_alert','انتظار يتجاوز الحد التوضيحي','waiting above illustrative limit');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-05','09:22','lg_assign','تمريض العيادة','Clinic nursing');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-05','09:24','lg_contact','تم التواصل','Contacted');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-05','09:25','lg_verify','احتياج مؤكد','Confirmed need');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-05','09:31','lg_status','تمت المعالجة','Resolved');
INSERT INTO cases VALUES ('A-06','الحالة أ-06','Case A-06',51,'em','contacting',0,'none',NULL,NULL,'open','11:05','انتظار 33 دقيقة في الطوارئ (حالة غير حرجة)','33 min ER wait (non-urgent)');
INSERT INTO case_signals (case_id,signal_key,weight,state,source,evidence_id,path_checked) VALUES ('A-06','wait',12,'active','sys','wait-5qrja',1);
INSERT INTO journey_events (case_id,what_ar,what_en,start_at,updated_at,place_code,place_source,source_ar,source_en,status,note_ar,note_en) VALUES ('A-06','انتظار الطوارئ — فرز غير حرج','ER waiting — non-urgent triage','10:32','11:05','er','sys','نظام الطوابير','Queue system','on',NULL,NULL);
INSERT INTO case_updates VALUES ('A-06','noans','open',NULL,NULL,'فريق تجربة المريض',NULL,NULL,NULL);
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-06','11:05','lg_alert','انتظار يتجاوز الحد التوضيحي','waiting above illustrative limit');
INSERT INTO follow_up_log (case_id,at,kind,value_ar,value_en) VALUES ('A-06','11:12','lg_contact','لم يرد','No answer');
